//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PleasantRustle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agents()
        {
            this.ProductRealization = new HashSet<ProductRealization>();
        }
    
        public int Id { get; set; }
        public string NameCompany { get; set; }
        public Nullable<int> AgentTypeId { get; set; }
        public string Adress { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string Director { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public byte[] Logo { get; set; }
        public int Priority { get; set; }
        public int Discount { get; set; }
        public virtual AgentTypes AgentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRealization> ProductRealization { get; set; }
    }
}
